import type { Metadata } from "next";
<<<<<<< HEAD
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { CURRENT_USER } from "@/data/mock";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WordWolf SNS",
  description: "言葉に気をつけろ。",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> yozure
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="ja">
      {/* ベースを黒背景・白文字に変更 */}
      <body className={`${inter.className} bg-gray-900 text-gray-200 antialiased min-h-screen relative`}>

        {/* ▼ 背景グラデーション (全ページ共通・固定表示) */}
        <div className="fixed inset-0 z-[-1] bg-gradient-to-br from-red-900 via-black to-gray-900 opacity-90 pointer-events-none"></div>

        {/* <Header currentUser={CURRENT_USER} /> */}
        <Header currentUser={null} />

        <div className="relative z-0">
          {children}
        </div>
      </body>
    </html>
  );
}
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
>>>>>>> yozure
