import type { Metadata } from "next";
<<<<<<< HEAD
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { CURRENT_USER } from "@/data/mock";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WordWolf SNS",
  description: "言葉に気をつけろ。",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> yozure
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="ja">
      {/* ▼ 修正箇所：className に bg-slate-50 と text-gray-900 を追加/確認してください */}
      <body className={`${inter.className} bg-slate-50 text-gray-900 antialiased`}>

        <Header currentUser={CURRENT_USER} />

        <div className="min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
>>>>>>> yozure
